CREATE TABLE [dbo].[PATIENT]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
	[CIVILITE] NVARCHAR(10) NOT NULL,
    [NOM_FAMILLE] NVARCHAR(75) NOT NULL, 
    [PRENOM] NVARCHAR(75) NOT NULL, 
    [RUE] NVARCHAR(MAX) NOT NULL, 
    [NUMERO] NVARCHAR(10) NOT NULL,
    [LOCALITE_ID] INT NOT NULL, 
    [DATE_NAISSANCE] DATETIME2 NULL, 
    [TELEPHONE] NVARCHAR(50) NULL, 
    [EMAIL] NVARCHAR(100) NULL, 
    [MEDECIN_TRAITANT] NVARCHAR(100) NULL, 
    [MEDECIN_TRAITANT_TELEPHONE] NVARCHAR(50) NULL, 
    [ETAT_SANTE_ID] INT NOT NULL,
    [STATUTENREGISTREMENT] BIT NOT NULL DEFAULT 1,
    CONSTRAINT [FK_PATIENT_ETATSANTE] FOREIGN KEY ([ETAT_SANTE_ID]) REFERENCES [ETAT_SANTE]([ID])

)
