CREATE TABLE [dbo].[SOIN]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    [DATE] DATETIME2 NOT NULL, 
    [TRAITEMENT] TEXT NULL, 
    [PANSEMENTS] TEXT NULL, 
    [CONSEILS] TEXT NULL, 
    [PATIENT_ID] INT NOT NULL, 
    CONSTRAINT [FK_SOIN_PATIENT] FOREIGN KEY ([PATIENT_ID]) REFERENCES [PATIENT]([ID])
)
